//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string meta { get; set; }
        public bool hide { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public bool able { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
