//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public bool able { get; set; }
        public string id { get; set; }
        public string symptom { get; set; }
        public string state { get; set; }
        public System.DateTime timeStart { get; set; }
        public System.DateTime timeEnd { get; set; }
        public string note { get; set; }
        public bool hide { get; set; }
        public string meta { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public string denid { get; set; }
        public string patid { get; set; }
    
        public virtual Dentist Dentist { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
