//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public string personId { get; set; }
        public string imgPath { get; set; }
        public System.DateTime uploadDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
