//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bill_Service = new HashSet<Bill_Service>();
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public string id { get; set; }
        public int totalPrice { get; set; }
        public int ServicesPrice { get; set; }
        public int PrescriptionPrice { get; set; }
        public bool able { get; set; }
        public bool hide { get; set; }
        public string meta { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public bool isPayed { get; set; }
        public string patid { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Service> Bill_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
