//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public string id { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string img { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public string zalo { get; set; }
        public string instagram { get; set; }
        public string youtube { get; set; }
        public bool hide { get; set; }
        public string meta { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public string title { get; set; }
        public string msg { get; set; }
        public System.DateTime dateStartClinic { get; set; }
    }
}
