//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumableMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsumableMaterial()
        {
            this.Ingredient_ConsumableMaterial = new HashSet<Ingredient_ConsumableMaterial>();
        }
    
        public string id { get; set; }
        public System.DateTime expDate { get; set; }
        public bool hide { get; set; }
        public string meta { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public bool able { get; set; }
    
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient_ConsumableMaterial> Ingredient_ConsumableMaterial { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
