//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient_ConsumableMaterial
    {
        public int able { get; set; }
        public string ingreId { get; set; }
        public string consumId { get; set; }
    
        public virtual ConsumableMaterial ConsumableMaterial { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
