//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public string id { get; set; }
        public string cateId { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public string calUnit { get; set; }
        public string func { get; set; }
        public System.DateTime mfgDate { get; set; }
        public bool able { get; set; }
        public bool hide { get; set; }
        public string meta { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public string img { get; set; }
    
        public virtual ConsumableMaterial ConsumableMaterial { get; set; }
        public virtual FixedMaterial FixedMaterial { get; set; }
        public virtual Material_Category Material_Category { get; set; }
    }
}
