//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Material
    {
        [DisplayName("Mã số")]
        public string id { get; set; }
        [DisplayName("Danh mục")]
        [Required(ErrorMessage = "Vui lòng chọn loại vật liệu.")]
        public string cateId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên vật liệu.")]
        [DisplayName("Tên vật liệu")]
        public string name { get; set; }
        [DisplayName("Số lượng")]
        [ValidPositiveInt]
        [Required(ErrorMessage = "Vui lòng nhập số lượng.")]
        public int quantity { get; set; }
        [DisplayName("Đơn vị")]
        [Required(ErrorMessage = "Vui lòng nhập đơn vị.")]
        public string calUnit { get; set; }
        [DisplayName("Chức năng")]
        [Required(ErrorMessage = "Vui lòng nhập chức năng.")]
        public string func { get; set; }
        [DisplayName("Ngày sản xuất")]
        [Required(ErrorMessage = "Vui lòng chọn ngày sản xuất.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime mfgDate { get; set; }
        public bool able { get; set; }
        [DisplayName("Hiển thị")]
        public bool hide { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập meta.")]
        public string meta { get; set; }
        [ValidPositiveInt]
        [DisplayName("Vị trí")]
        [Required(ErrorMessage = "Vui lòng nhập vị trí.")]
        public int new_order { get; set; }
        public int order { get; set; }
        [DisplayName("Ngày cập nhật")]
        public System.DateTime datebegin { get; set; }
        [DisplayName("Hình ảnh")]
        public string img { get; set; }

        public virtual ConsumableMaterial ConsumableMaterial { get; set; }
        public virtual FixedMaterial FixedMaterial { get; set; }
        public virtual Material_Category Material_Category { get; set; }
    }
}
