//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NEWS
    {
        [DisplayName("Mã số")]
        public string id { get; set; }

        [DisplayName("Hình ảnh")]
        public string img { get; set; }

        [DisplayName("Tiêu đề")]
        [Required(ErrorMessage = "Vui lòng nhập tiêu đề.")]
        public string title { get; set; }


        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả.")]
        public string descrip { get; set; }


        [DisplayName("Nội dung")]
        [Required(AllowEmptyStrings = true)]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string msg { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập meta.")]
        public string meta { get; set; }

        [DisplayName("Hiển thị")]
        public bool hide { get; set; }
        
        [DisplayName("Vị trí")]
        [Required(ErrorMessage = "Vui lòng nhập thứ tự.")]
        public int order { get; set; }

        [DisplayName("Vị trí")]
        [Required(ErrorMessage = "Vui lòng nhập vị trí.")]
        [ValidPositiveInt]
        public int new_order { get; set; }

        [DisplayName("Ngày cập nhật")]
        public System.DateTime datebegin { get; set; }
    }
}
