//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Calendars = new HashSet<Calendar>();
        }
    
        public string meta { get; set; }
        public bool hide { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public int salary { get; set; }
        public string address { get; set; }
        public bool gender { get; set; }
        public System.DateTime birthday { get; set; }
        public string nation { get; set; }
        public int role { get; set; }
        public string img { get; set; }
        public string id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Assisstant Assisstant { get; set; }
        public virtual Avatar Avatar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual Dentist Dentist { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Receptionist Receptionist { get; set; }
    }
}
