//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Prescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescription()
        {
            this.Prescription_Medicine = new HashSet<Prescription_Medicine>();
        }
        [DisplayName("Mã số")]
        public string id { get; set; }
        [DisplayName("Ghi chú")]
        [Required(ErrorMessage = "Vui lòng nhập ghi chú.")]
        public string note { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá.")]
        [DisplayName("Giá")]
        [ValidPositiveInt]
        public int price { get; set; }
        [DisplayName("Hiển thị")]
        public bool hide { get; set; }
        [DisplayName("Trạng thái")]
        public bool able { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập meta.")]
        public string meta { get; set; }
        public int order { get; set; }
        [ValidPositiveInt]
        [DisplayName("Vị trí")]
        [Required(ErrorMessage = "Vui lòng nhập vị trí.")]
        public int new_order { get; set; }
        [DisplayName("Ngày cập nhật")]
        public System.DateTime datebegin { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá.")]
        [DisplayName("Nha sĩ")]
        public string denid { get; set; }
        [DisplayName("Bệnh nhân")]
        public string patid { get; set; }
        public string billid { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Dentist Dentist { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Medicine> Prescription_Medicine { get; set; }
    }
}
