//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Bill_Service = new HashSet<Bill_Service>();
        }
    
        public string id { get; set; }
        public string cateId { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public string note { get; set; }
        public string descrip { get; set; }
        public string caredActor { get; set; }
        public string meta { get; set; }
        public bool hide { get; set; }
        public bool able { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public string calUnit { get; set; }
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Service> Bill_Service { get; set; }
        public virtual Service_Category Service_Category { get; set; }
    }
}
