//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentalcare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Bill_Service = new HashSet<Bill_Service>();
        }

        [DisplayName("Mã số")]

        public string id { get; set; }
        [DisplayName("Danh mục")]
        [Required(ErrorMessage = "Vui lòng chọn loại dịch vụ.")]
        public string cateId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên dịch vụ.")]
        [DisplayName("Tên dịch vụ")]
        public string name { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá.")]
        [DisplayName("Giá")]
        [ValidPositiveInt]
        public int price { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [DisplayName("Ghi chú")]
        public string note { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mô tả.")]
        [DisplayName("Mô tả")]
        public string descrip { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập đối tượng chữa trị.")]
        [DisplayName("Đối tượng chữa trị")]
        public string caredActor { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập meta.")]
        public string meta { get; set; }

        [DisplayName("Hiển thị")]
        public bool hide { get; set; }
        
        [ValidPositiveInt]
        [DisplayName("Vị trí")]
        [Required(ErrorMessage = "Vui lòng nhập vị trí.")]
        public int order { get; set; }

        [ValidPositiveInt]
        [DisplayName("Vị trí")]
        [Required(ErrorMessage = "Vui lòng nhập vị trí.")]
        public int new_order { get; set; }

        [DisplayName("Ngày cập nhật")]
        public System.DateTime datebegin { get; set; }
        [DisplayName("Đơn vị")]
        [Required(ErrorMessage = "Vui lòng nhập đơn vị.")]
        public string calUnit { get; set; }

        [DisplayName("Hình ảnh")]
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Service> Bill_Service { get; set; }

        [DisplayName("Loại dịch vụ")]
        public virtual Service_Category Service_Category { get; set; }
    }
}
